#!/bin/bash

# Set paths for the PDF.js build and target directories
PDFJS_BUILD=./reader/pdfjs/pdf.js/build/generic-legacy
PDFJS_MINIFIED_BUILD=./reader/pdfjs/pdf.js/build/minified-legacy
BUILD_BASE=./reader/build

# Move into the PDF.js directory, install dependencies, and build
cd reader/pdfjs/pdf.js
npm ci
# Zotero with FF 115 ESR runs only the `legacy` build
npx gulp generic-legacy
npx gulp minified-legacy
cd ../../../

# Set up directories for dev build
BUILD=dev
BUILD_DIR="$BUILD_BASE/$BUILD/pdf"
rm -rf "$BUILD_DIR"
mkdir -p "$BUILD_DIR/build"
mkdir -p "$BUILD_DIR/web/images"
cp -r "$PDFJS_BUILD/LICENSE" "$BUILD_DIR/"
cp -r "$PDFJS_BUILD/build/pdf.mjs" "$BUILD_DIR/build/"
cp -r "$PDFJS_BUILD/build/pdf.worker.mjs" "$BUILD_DIR/build/"
cp -r "$PDFJS_BUILD/web/cmaps" "$BUILD_DIR/web/"
cp -r "$PDFJS_BUILD/web/standard_fonts" "$BUILD_DIR/web/"
cp -r "$PDFJS_BUILD/web/iccs" "$BUILD_DIR/web/"
cp -r "$PDFJS_BUILD/web/wasm" "$BUILD_DIR/web/"
cp -r "$PDFJS_BUILD/web/viewer.html" "$BUILD_DIR/web/"
cp -r "$PDFJS_BUILD/web/viewer.mjs" "$BUILD_DIR/web/"
cp -r "$PDFJS_BUILD/web/images/loading-icon.gif" "$BUILD_DIR/web/images/"
cp -r "./reader/pdfjs/viewer.css" "$BUILD_DIR/web/"

# Set up directories for obsidian build
BUILD=obsidian
BUILD_DIR="$BUILD_BASE/$BUILD/pdf"
rm -rf "$BUILD_DIR"
mkdir -p "$BUILD_DIR/build"
mkdir -p "$BUILD_DIR/web/images"
cp -r "$PDFJS_BUILD/LICENSE" "$BUILD_DIR/"
cp -r "$PDFJS_BUILD/build/pdf.mjs" "$BUILD_DIR/build/"
cp -r "$PDFJS_BUILD/build/pdf.worker.mjs" "$BUILD_DIR/build/"
cp -r "$PDFJS_BUILD/web/cmaps" "$BUILD_DIR/web/"
cp -r "$PDFJS_BUILD/web/standard_fonts" "$BUILD_DIR/web/"
cp -r "$PDFJS_BUILD/web/iccs" "$BUILD_DIR/web/"
cp -r "$PDFJS_BUILD/web/wasm" "$BUILD_DIR/web/"
cp -r "$PDFJS_BUILD/web/viewer.html" "$BUILD_DIR/web/"
cp -r "$PDFJS_BUILD/web/viewer.mjs" "$BUILD_DIR/web/"
cp -r "$PDFJS_BUILD/web/images/loading-icon.gif" "$BUILD_DIR/web/images/"
cp -r "./reader/pdfjs/viewer.css" "$BUILD_DIR/web/"
